---
functional:
  - Пользователь должен иметь возможность зарегестрироваться на сайте
  - Пользователь должен иметь возможность зарегистрироваться с помощью Github
  - Пользователь должен иметь возможность зарегистрироваться с помощью Discord
  - Пользователь должен иметь возможность авторизоваться с помощью логина и пароля
  - Пользователь должен иметь возможность авторизоваться с помощью Github
  - Пользователь должен иметь возможность авторизоваться с помощью Discord
  - Пользователь должен иметь возможность попробовать игру без регистрации
  - Пользователь должен иметь возможность восстанавливать пароль
  - Пользователь должен иметь возможность выбрать игру по уровню сложности
  - Пользователь должен иметь возможность приглашать в игру других пользователей
  - Пользователь должен иметь возможность выбрать игру с ботом
  - Пользователь должен иметь возможность создать игру
  - Пользователь должен иметь возможность вступать в открытые игры
  - Пользователь должен иметь возможность зайти в запущенную игру в качестве зрителя
  - Пользователь должен иметь возможность во время игры выбрать другой язык программирования
  - Пользователь должен иметь возможность во время игры сбросить редактор кода
  - Пользователь должен иметь возможность общаться в чате игры со своим соперником
  - Пользователь должен иметь возможность просматривать рейтинг участников за неделю, месяц и за все время
  - Пользователь должен иметь возможность общаться в чате с другими зарегистрированными пользователями
  - Пользователь должен иметь возможность выбрать отображение задачи на английском и русском языке
  - Пользователь должен иметь возможность прервать игру
non-functional:
  - Сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы
  - Проверка UX/UI написания элементов на грамматические ошибки, удобный вывод на странице
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен быть адаптивным и удобным на мобильных устройствах
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров
  - Сайт должен быть способен обрабатывать большое количество трафика
  - Сайт должен быть доступен на различных устройствах
implicit:
  - Сайт должен быть безопасным и защищать данные пользователя
  - Во время регистрации и входа в систему, если введены не корректные данные, то система должна выдать сообщение об ошибке
  - Пользователь должен иметь возможность подписываться на других пользователей
  - Пользователь не должен иметь возможность редактировать код в завершенной игре
  - У пользователей должна быть возможность объединяться в команды для проведения турниров с другими командами  
